name: PureScript Tests
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: purescript-contrib/setup-purescript@main
        with:
          purescript: "0.15.10"
          spago: "0.21.0"
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm install
      - run: spago build
      - run: spago test

